### PR TITLE
Update to Forge 40.0.31 (e5d4e5d3a)

### PR DESCRIPTION
**Pull request by m1lc0lm**

### CODE REVIEW

**Comment by UeberallGebannt** [comment]
Why did you close the PR?

**Comment by m1lc0lm** [comment]
Cause there is code, that shouldnt be in there

**Comment by m1lc0lm** [comment]
I was testing with nms

**Comment by m1lc0lm** [comment]
I

**Comment by m1lc0lm** [comment]
I had to remove the NMS shit cause it not work yet

**Pull request merged**
